[windows]
o3 = '7d'
o4-mini-high = '1d'
o4-mini = '1d'
"GPT-4.5" = '7d'
"GPT-5" = '3h'
"GPT-5-Thinking" = '7d'

[limits]
o3 = 100
o4-mini-high = 100
o4-mini = 300
"GPT-4.5" = 15
"GPT-5" = 160
"GPT-5-Thinking" = 3000